package rajlee.com.demoapi.service.impl;


import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import rajlee.com.demoapi.dto.StudentDto;
import rajlee.com.demoapi.entity.Student;
import rajlee.com.demoapi.exception.ResourceNotFoundException;
import rajlee.com.demoapi.repository.StudentRepository;
import rajlee.com.demoapi.service.StudentService;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class StudentServiceImpl implements StudentService {

    private final StudentRepository studentRepository;

    @Override
    public List<StudentDto> getAllStudents() {
        return studentRepository.findAll().stream()
                .map(this::mapToDto)
                .toList();
    }

    @Override
    public StudentDto getStudentById(UUID id) {
        Student student = studentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with ID: " + id));
        return mapToDto(student);
    }

    @Override
    public StudentDto createStudent(StudentDto dto) {
        // ID is auto-generated by Hibernate, so we pass null or just use a constructor that doesn't take ID if available
        Student student = new Student(null, dto.firstName(), dto.lastName(), dto.dob(), dto.address());
        Student savedStudent = studentRepository.save(student);
        return mapToDto(savedStudent);
    }

    @Override
    public StudentDto updateStudent(UUID id, StudentDto dto) {
        Student existingStudent = studentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with ID: " + id));

        existingStudent.setFirstName(dto.firstName());
        existingStudent.setLastName(dto.lastName());
        existingStudent.setDob(dto.dob());
        existingStudent.setAddress(dto.address());

        Student updatedStudent = studentRepository.save(existingStudent);
        return mapToDto(updatedStudent);
    }

    @Override
    public void deleteStudent(UUID id) {
        Student student = studentRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Student not found with ID: " + id));
        studentRepository.delete(student);
    }

    // Helper method for mapping (Consider using MapStruct for larger projects)
    private StudentDto mapToDto(Student student) {
        return new StudentDto(
                student.getId(),
                student.getFirstName(),
                student.getLastName(),
                student.getDob(),
                student.getAddress()
        );
    }
}